# INFO: Combined inventory file — hosts + constructed grouping
plugin: ansible.builtin.constructed

# INFO: Allow hosts that do not match any rule without failing
strict: false

# INFO: Define dynamic groups based on hostname patterns
groups:

  # INFO: Base classification
  servers: inventory_hostname.startswith('srv-')
  workstations: inventory_hostname.startswith('ws-')