# ------------------------------------------------------------
# NOTE: Servers
# ------------------------------------------------------------

# Servers IaC
servers_raspberrypi:
  hosts:
    srv-pi[0:9]:

# Servers IaC
servers_iac:
  hosts:
    srv-lxc-iac[p:s][0:9]:    

# Servers Utility
servers_utility:
  hosts:
    srv-utl[p:s][0:9]:

# NOTE: Server Groups
servers:
  children:
    servers_raspberrypi:
    servers_iac:
    servers_utility:

# NOTE: Proxmox servers

proxmox_vm:         # INFO: For installing qemu-guest-agent on Proxmox VM's (base | tasks | main | packages_base_qemu_agent.yml)
  children:
    servers_utility: # All Utility Servers

# ------------------------------------------------------------
# NOTE: Workstations
# ------------------------------------------------------------

# Workstations General
workstations_general:
  hosts:
    ws-gen[p:s][0:9]:

# Workstations Development
workstations_dev:
  hosts:
    ws-dev[p:s][0:9]:
    

# NOTE: Workstation Groups
workstations:
  children:
    workstations_general:
    workstations_dev: