# NOTE: Servers

# Servers Utility
servers_utility:
  hosts:
    srv-utls[0:9]:
    srv-utlp[0:9]:

# Servers IAC
servers_iac:
  hosts:
    srv-iacs[0:9]:
    srv-iacp[0:9]:

# NOTE: Workstations

# Workstations General
workstations_general:
  hosts:
    ws-gen[0:9]:
    ws-gens[0:9]:
    ws-genp[0:9]:

# Workstations Development
workstations_dev:
  hosts:
    ws-dev[0:9]:
    ws-devs[0:9]:
    ws-devp[0:9]:
    
# NOTE: Groups

# INFO: Server Groups
servers:
  children:
    servers_utility:
    servers_iac:

# INFO: Workstation Groups
workstations:
  children:
    workstations_general:
    workstations_dev:

# INFO: Proxmox Instances

# HACK: ansble-pull can't recognize regex very well (`ws-devs[0:9]`). Defined groups instead to install `qemu-agent` on proxmox VM's.

# Workstations General
workstations_general_s:
  hosts:
    ws-gens[0:9]:

# Workstations Development
workstations_dev_s:
  hosts:
    ws-devs[0:9]:

proxmox:
  children:
    servers_utility: # All Utility Servers
    servers_iac:     # All IAC Servers
    workstations_general_s: # HACK: Worktations General Staging
    workstations_dev_s:     # HACK: Worktations Dev Staging 