# NOTE: Servers

# Servers Utility
servers_utility:
  hosts:
    srv-utls[0:9]:
    srv-utlp[0:9]:

# Servers IAC
servers_iac:
  hosts:
    srv-iacs[0:9]:
    srv-iacp[0:9]:

# NOTE: Workstations

# Workstations General
workstations_general:
  hosts:
    ws-gens[0:9]:
    ws-genp[0:9]:

# Workstations Development
workstations_dev:
  hosts:
    ws-devs[0:9]:
    ws-devp[0:9]:
    
# NOTE: Groups

# INFO: Server Groups
servers:
  children:
    servers_utility:
    servers_iac:

# INFO: Workstation Groups
workstations:
  children:
    workstations_general:
    workstations_dev:

# INFO: Proxmox Instances
proxmox:
  children:
    servers_utility: # All Utility Servers
    servers_iac:     # All IAC Servers  
    ws-gens[0:9]:    # All General Workstations in Staging
    ws-devs[0:9]:    # All Dev Workstations in Staging