# tasks to complete before running roles
- hosts: servers_iac
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: always