all:
  children:
    common: # All machines - use wildcards?
      hosts:
        stg-srv-iac-01:
        stg-srv-docker-01:
        stg-srv-util-01:
        stg-dsk-dev-01:
        stg-dsk-gen-01:
        prod-srv-iac-01:
        prod-srv-docker-01:
        prod-dsk-dev-01:
        prod-dsk-gen-01:

    servers:
      children:
        server_iac:
          hosts:
            stg-srv-iac-01:
            prod-srv-iac-01:
        server_docker:
          hosts:
            stg-srv-docker-01:
            prod-srv-docker-01:
        server_swarm_manager:
          hosts:
            stg-srv-docker-01:
        server_swarm_host:
          hosts:
            stg-srv-docker-01:
        server_utility:
          hosts:
            stg-srv-util-01:

    desktops:
      children:
        desktop_general:
          hosts:
            stg-dsk-gen-01:
            prod-dsk-gen-01:
        desktop_development:
          hosts:
            stg-dsk-dev-01:
            prod-dsk-dev-01:

    prod:
      hosts:
        prod-srv-iac-01:
        prod-srv-docker-01:
        prod-dsk-dev-01:
        prod-dsk-gen-01:

    stg:
      hosts:
        stg-srv-iac-01:
        stg-srv-docker-01:
        stg-srv-util-01:
        stg-dsk-dev-01:
        stg-dsk-gen-01: