servers:
  hosts:
    srv-iacp[1:9]:
    srv-iacs1[1:9]:
    srv-utlp1[1:9]:
    srv-utls1[1:9]:

workstations:
  hosts:
    ws-genp1[1:9]:
    ws-devp1[1:9]:
    ws-gens1[1:9]:
    ws-devs1[1:9]:

servers_iac:
  hosts: 
    srv-iacp1[1:9]:
    srv-iacs1[1:9]:

servers_utility:
  hosts: 
    srv-utlp1[1:9]:
    srv-utls1[1:9]:   

workstations_general:
  hosts:
    ws-genp1[1:9]:
    ws-gens1[1:9]:

workstations_dev:
  hosts:
    ws-devp1[1:9]:
    ws-devs1[1:9]:


k3s:
  children:
    k3smgr:
    k3slb:     
    k3ssvr:


