# INFO: Static host list for dynamic inventory classification
all:
  hosts:
    # INFO: Servers
    srv-iacs1:
    srv-iacp1:
    srv-utls1:
    srv-utlp1:
    srv-docker-mgrp1:
    srv-docker-hostp1:
    srv-docker-mgrs1:
    srv-docker-hosts1:    

    # INFO: Workstations
    ws-gens1:
    ws-genp1:
    ws-devs1:
    ws-devp1: 